### ISSUE TITLE
Remove Your First PR link

### ISSUE THREAD

**Issue by HypnotizedLeda** [github/opensourcefriday#1103]
The project (Your First PR) has been inactive for a while now, so perhaps it would be better to remove it?

Their Tweet Regarding Activity:

![image](https://user-images.githubusercontent.com/38331868/142751508-9f3a373c-1d7d-4516-9b69-be78f5a5a847.png)

**Comment by BaseMax** [comment]
Hi Leda,

It seems you are right.

**Related links:**
- https://twitter.com/yourfirstpr
- https://yourfirstpr.github.io/
- https://github.com/yourfirstpr
- https://github.com/yourfirstpr/yourfirstpr.github.io

Anyway, we can ask "Your first PR" organizer, Dear James.
CC @varjmes

**Comment by MikeMcQuaid** [comment]
👍🏻 agreed. Could one of you submit a PR to remove all these links? Thanks!

**Comment by BaseMax** [comment]
Yeah sure, I want to do it. ☺️

**Comment by smashwilson** [comment]
Fixed by #1119. Thank you! 🙇🏻
