### ISSUE TITLE
Help me out in setting up environment

### ISSUE THREAD

**Issue by MangiNikhil** [github/opensourcefriday#1262]
I'm having a issue while running it on my local machine

Using windows Os .
can any one tell me how to setup i'm new to open source help me out

**Comment by zkoppert** [comment]
Is there a specific error you are running into? THe instructions for setting this up are documented at https://github.com/github/opensourcefriday#getting-started

**Comment by jonasermert** [comment]
Please make a screenshot of the terminal. So, it's easier to help.

**Comment by ahpook** [comment]
Closing, I don't think we can help with this.
