### ISSUE TITLE
Add a sticky navbar 

### ISSUE THREAD

**Issue by Pranaam19** [github/opensourcefriday#1263]
Hi was going through the website and found that the website lacks sticky navbar. Having one will make it easy for the viewers to go through different sections of the website.
I would like help in creating a sticky navbar for the website.

**Comment by vipinnation** [comment]
I want to work on this issue

**Comment by nidhipawar5** [comment]
Hey I'm working on this, please assign

**Comment by nidhipawar5** [comment]
Hi, I've submitted a pull request regarding this feature/fix, requesting a review. Thanks.

**Comment by ipc103** [comment]
👋 Hi folks, thanks for the contribution, but we're happy with the current look and functionality of the navbar at this time.
