### ISSUE TITLE
Start contributing to this repository

### ISSUE THREAD

**Issue by jonasermert** [github/opensourcefriday#1268]
Hello, I want to contribute, but there are no open issues. What can I do?

**Comment by arunsathiya** [comment]
This repository seems to be the source code for the website itself. If you are looking to get started with open source contributions, depending on your developer tooling interests, you may like to search by language and then look for issues labelled `good first issue`, `needs help`, `help wanted`, etc. 

The homepage of Open Source Friday also seems to link to Up for Grabs and Code Triage platforms, which you can use too:

![image](https://github.com/github/opensourcefriday/assets/18581859/4da89220-4e1d-4288-81cc-0737eac2cf6a)

Personally, I am working on sharpening my Golang knowledge, so I contribute to projects like [GH CLI](http://github.com/cli/cli/) and [1Password Shell Plugins](http://github.com/1password/shell-plugins/).

**Comment by ahpook** [comment]
As @arunsathiya points out, this repo doesn't have much activity because it only contains the source code for the https://opensourcefriday.com website, which is pretty static. I hope you find a good project to work on, though!
