### ISSUE TITLE
Remove node_modules from Git

### ISSUE THREAD

**Issue by MikeMcQuaid** [github/opensourcefriday#563]
These were originally added to ease deployment on Heroku but can easily become out of sync (partial fix in https://github.com/github/opensourcefriday/pull/561).

Instead, it would be preferable to remove `node_modules` from Git and instead use an additional Heroku build pack to ensure `npm install` is run before the application is run (e.g. https://stackoverflow.com/a/22850632/5355).

Note if this is done there will need to be some workaround to handle e.g. newer versions of Primer removing CSS rules that are used (e.g. `alt-h0`).

See https://github.com/github/opensourcefriday/pull/562 for a related PR.

**Comment by kenyonj** [comment]
This looks good @mikemcquaid. Thanks for looking into this. However, Site Engineering no longer owns this repo. As of August 2018 it has been transferred over to @github/developer-relations.

**Comment by bdougie** [comment]
Circling back here. Who is an admin on this repo that can make me one? I am unable to merge and happy to help.

**Comment by talsafran** [comment]
I got you @bdougie! 🙌 

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/257028/74073413-1a79ea00-49bf-11ea-9822-e51245090b66.png">

**Comment by MikeMcQuaid** [comment]
Assigning to @gallexi (not because it's on you to deal with this but you're so 💖 at triaging that I'm sure you'll get this with the right people)!
