### ISSUE TITLE
Need a better quality in Persian website

### ISSUE THREAD

**Issue by BaseMax** [github/opensourcefriday#585]
Hello GitHub,

We hope the open source Friday campaign to be useful for everyone.

My plan to improve Open Source Friday in Persian:

- Adding a Persian and open-source font.
- Keep `?locale=**` when switch between pages.
- Adding rtl direction and modify **CSS** styles.
- Adding some words not in locale `yml` files.

I use here as a share space to work on this subject.

I will inform after any activity at here.

At first, I need permission from administrators.
We can continue? @MikeMcQuaid

Best,
Max Base

**Comment by bdougie** [comment]
Hi @BaseMax, you can use the [CONTRIBUTING.md](https://github.com/github/opensourcefriday/blob/master/CONTRIBUTING.md#translation) as a guide.

There are also rubygems that handle the rtl conversion? Are you familiar with https://github.com/abarrak/rtl or other solutions to handle the CSS dynamically?

**Comment by MikeMcQuaid** [comment]
Thanks @BaseMax, closing this for now as it's not actionable for us but look forward to any PRs.
