### ISSUE TITLE
Miss a Chinese character

### ISSUE THREAD

**Issue by hezhizhen** [github/opensourcefriday#922]
<img width="694" alt="截屏2021-03-15 20 14 15" src="https://user-images.githubusercontent.com/7611700/111152058-422c8000-85cb-11eb-8e24-21e4f8e30731.png">

I've tried to create a PR to fix it, but I didn't find where the content was.

**Comment by hezhizhen** [comment]
I found it and created a PR to fix it: https://github.com/github/opensource.guide/pull/2268

**Comment by jace833** [comment]
我

**Comment by jace833** [comment]
> <img alt="截屏2021-03-15 20 14 15" width="694" src="https://user-images.githubusercontent.com/7611700/111152058-422c8000-85cb-11eb-8e24-21e4f8e30731.png">
> 
> I've tried to create a PR to fix it, but I didn't find where the content was.

你
